#!/bin/sh

. "$HOME"/.local/bin/bar-colors

state="$(cat /sys/class/power_supply/BAT*/status)"
percent="$(cat /sys/class/power_supply/BAT*/capacity)"

if [ "$percent" -lt 10 ]; then
    icon="$FG_RED 󰂎"
elif [ "$percent" -le 30 ]; then
    icon="$FG_ORANGE 󰁻"
elif [ "$percent" -le 60 ]; then
    icon="$FG_GREEN 󰁽"
elif [ "$percent" -le 90 ]; then
    icon="$FG_GREEN 󰂀"
else
    icon="$FG_GREEN 󰁹"
fi

case $state in
 "Charging" ) charge="$FG_YELLOW 󰚥" ;;
esac

case $BUTTON in
    1) notify-send -a Battery "$(acpi | cut -c 12-)"
esac

echo "$BG_DARK$icon $charge $percent% ^d^"
