#!/bin/sh

cat /tmp/recordingicon

updateicon() {
    echo "$1" > /tmp/recordingicon
    pkill -RTMIN+9 hydrablocks
}

killrecording(){
    recpid="$(cat /tmp/recordingpid)"
    # kill with SIGTERM, allowing finishing touches.
    kill -15 "$recpid"
    rm -f /tmp/recordingpid
    updateicon ""
    pkill -RTMIN+9 hydrablocks
    # even after SIGTERM, ffmpeg may still run, so SIGKILL it.
    sleep 3
    kill -9 "$recpid"
	videonotify
}

case $BUTTON in
	1) [ -f /tmp/recordingpid ] && killrecording ;;
esac
