#!/bin/sh

. "$HOME"/.local/bin/bar-colors

state="$(mpc | sed '2!d ; s/ .*//')"

icon=""
case $state in
	"[playing]") icon=" " ;;
	"[paused]") icon=" " ;;
	*) icon="" ;;
esac

text="$(tail -n1 /tmp/mpcscroll | sed 's/^/ /')"

case $text in
	" ") exit 0 ;;
	*) echo "$FG_RED$BG_DARK $icon $text ^d^";;
esac

case $BUTTON in
	1) mpc toggle ;;  # left click pause/unpause
	3) setsid -f "$TERMINAL" -c ncmpcpp -e ncmpcpp ;;  # right click, open ncmpcpp
	4) mpc volume +1 ;; # scrollup, volume up
	5) mpc volume -1 ;; # scolldown, volume down
esac
