#!/bin/sh

. "$HOME"/.local/bin/bar-colors

case $BUTTON in
	2) pamixer -t ;;
	3) pavucontrol ;;
	4) pamixer --allow-boost -i 1 ;;
	5) pamixer --allow-boost -d 1 ;;
esac

[ $(pamixer --get-mute) = true ] && echo "$BG_DARK$FG_PINK  󰝟  ^d^" && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon="󰕾"
elif [ "$vol" -lt "30" ]; then
	icon="󰕿"
else
	icon="󰖀"
fi

echo "$BG_DARK$FG_PINK $icon $vol% ^d^"
