#!/bin/sh

. "$HOME"/.local/bin/bar-colors

FILE=/tmp/bar-clock
bgcolor=$BG_DARK
fgcolor=$FG_LIGHTBLUE

case $BUTTON in
    1) notify-send -a "Date" "$(date '+%A, %d %B %Y')" ;;
    3) flatpak run org.gnome.Calendar ;;
esac

togglecolor(){
    if [ -f "$FILE" ]; then
        rm $FILE
        bgcolor=$bg
        fgcolor=$lightblue
    else
        touch $FILE
        # bgcolor=
    fi
}

echo "$bgcolor$fgcolor   $(date '+%H:%M') ^d^  "
