#!/bin/sh

export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
export vblank_mode=0

export PATH=/opt/wine-osu/bin:$PATH

export WINEPREFIX=/mnt/KINGSTON/osu!/
export WINEARCH=win32

export STAGING_AUDIO_PERIOD=14000

wine /mnt/KINGSTON/osu!/drive_c/users/nytou/AppData/Local/osu!/osu!.exe "$@"
