#!/bin/sh

# DMENUOPTS="-x 6 -y 6 -z 1908 -i"
DMENUOPTS="-x 0 -y 0 -z 1920 -i"
# DMENUOPTS="-x 560 -y 980 -z 800"

choice=$(printf "poweroff\\nreboot\\nsuspend\\nlock\\nexit" | dmenu $DMENUOPTS -p "⏻ ")
case "$choice" in
    poweroff) poweroff ;;
    reboot) reboot ;;
    suspend) systemctl suspend ;;
    lock) lock ;;
    exit) kill -15 $(pidof hydra) ;;
esac
