#!/bin/sh

folder="$HOME/pics/screenshots"
filename="$(/usr/bin/ls "$folder" -t | head -n 1)"
fileloc="$folder/$filename"

xclip -selection clipboard -t image/png "$fileloc"
notify-send --app-name="Screenshot saved" "$filename" --icon="$fileloc"
