# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/606e1337-3dfd-47ba-bc44-b806515b3a1f";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-1227c54f-76c5-45d5-aa7c-f3f2dd3a77a2".device = "/dev/disk/by-uuid/1227c54f-76c5-45d5-aa7c-f3f2dd3a77a2";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5991-2F5E";
      fsType = "vfat";
    };

  fileSystems."/mnt/KINGSTON" =
    { device = "/dev/disk/by-uuid/00666f31-59fa-4d9c-9ae2-415127e27a7d";
      fsType = "btrfs";
      # options = [ "subvol=@" "compress=zstd" "noatime" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/3c6e85a3-ee2c-44b3-9c5b-86b2721a5537"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
